// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: match_engine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	// 创建订单
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	// 取消订单
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	// 查询订单
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	// 查询用户订单
	GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...grpc.CallOption) (*GetUserOrdersResponse, error)
	// 批量创建订单
	BatchCreateOrders(ctx context.Context, in *BatchCreateOrdersRequest, opts ...grpc.CallOption) (*BatchCreateOrdersResponse, error)
	// 批量取消订单
	BatchCancelOrders(ctx context.Context, in *BatchCancelOrdersRequest, opts ...grpc.CallOption) (*BatchCancelOrdersResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, "/matchengine.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, "/matchengine.OrderService/CancelOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, "/matchengine.OrderService/GetOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetUserOrders(ctx context.Context, in *GetUserOrdersRequest, opts ...grpc.CallOption) (*GetUserOrdersResponse, error) {
	out := new(GetUserOrdersResponse)
	err := c.cc.Invoke(ctx, "/matchengine.OrderService/GetUserOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) BatchCreateOrders(ctx context.Context, in *BatchCreateOrdersRequest, opts ...grpc.CallOption) (*BatchCreateOrdersResponse, error) {
	out := new(BatchCreateOrdersResponse)
	err := c.cc.Invoke(ctx, "/matchengine.OrderService/BatchCreateOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) BatchCancelOrders(ctx context.Context, in *BatchCancelOrdersRequest, opts ...grpc.CallOption) (*BatchCancelOrdersResponse, error) {
	out := new(BatchCancelOrdersResponse)
	err := c.cc.Invoke(ctx, "/matchengine.OrderService/BatchCancelOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility
type OrderServiceServer interface {
	// 创建订单
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	// 取消订单
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	// 查询订单
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	// 查询用户订单
	GetUserOrders(context.Context, *GetUserOrdersRequest) (*GetUserOrdersResponse, error)
	// 批量创建订单
	BatchCreateOrders(context.Context, *BatchCreateOrdersRequest) (*BatchCreateOrdersResponse, error)
	// 批量取消订单
	BatchCancelOrders(context.Context, *BatchCancelOrdersRequest) (*BatchCancelOrdersResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (UnimplementedOrderServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServiceServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetUserOrders(context.Context, *GetUserOrdersRequest) (*GetUserOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrders not implemented")
}
func (UnimplementedOrderServiceServer) BatchCreateOrders(context.Context, *BatchCreateOrdersRequest) (*BatchCreateOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCreateOrders not implemented")
}
func (UnimplementedOrderServiceServer) BatchCancelOrders(context.Context, *BatchCancelOrdersRequest) (*BatchCancelOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchCancelOrders not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.OrderService/CancelOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.OrderService/GetOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetUserOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetUserOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.OrderService/GetUserOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetUserOrders(ctx, req.(*GetUserOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_BatchCreateOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCreateOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).BatchCreateOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.OrderService/BatchCreateOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).BatchCreateOrders(ctx, req.(*BatchCreateOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_BatchCancelOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCancelOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).BatchCancelOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.OrderService/BatchCancelOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).BatchCancelOrders(ctx, req.(*BatchCancelOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchengine.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _OrderService_CancelOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _OrderService_GetOrder_Handler,
		},
		{
			MethodName: "GetUserOrders",
			Handler:    _OrderService_GetUserOrders_Handler,
		},
		{
			MethodName: "BatchCreateOrders",
			Handler:    _OrderService_BatchCreateOrders_Handler,
		},
		{
			MethodName: "BatchCancelOrders",
			Handler:    _OrderService_BatchCancelOrders_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "match_engine.proto",
}

// MarketDataServiceClient is the client API for MarketDataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MarketDataServiceClient interface {
	// 获取订单簿快照
	GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error)
	// 订阅订单簿更新
	SubscribeOrderBook(ctx context.Context, in *SubscribeOrderBookRequest, opts ...grpc.CallOption) (MarketDataService_SubscribeOrderBookClient, error)
	// 获取最近成交
	GetRecentTrades(ctx context.Context, in *GetRecentTradesRequest, opts ...grpc.CallOption) (*GetRecentTradesResponse, error)
	// 订阅成交
	SubscribeTrades(ctx context.Context, in *SubscribeTradesRequest, opts ...grpc.CallOption) (MarketDataService_SubscribeTradesClient, error)
	// 获取行情数据
	GetTicker(ctx context.Context, in *GetTickerRequest, opts ...grpc.CallOption) (*GetTickerResponse, error)
}

type marketDataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketDataServiceClient(cc grpc.ClientConnInterface) MarketDataServiceClient {
	return &marketDataServiceClient{cc}
}

func (c *marketDataServiceClient) GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error) {
	out := new(GetOrderBookResponse)
	err := c.cc.Invoke(ctx, "/matchengine.MarketDataService/GetOrderBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) SubscribeOrderBook(ctx context.Context, in *SubscribeOrderBookRequest, opts ...grpc.CallOption) (MarketDataService_SubscribeOrderBookClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketDataService_ServiceDesc.Streams[0], "/matchengine.MarketDataService/SubscribeOrderBook", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketDataServiceSubscribeOrderBookClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketDataService_SubscribeOrderBookClient interface {
	Recv() (*OrderBookUpdate, error)
	grpc.ClientStream
}

type marketDataServiceSubscribeOrderBookClient struct {
	grpc.ClientStream
}

func (x *marketDataServiceSubscribeOrderBookClient) Recv() (*OrderBookUpdate, error) {
	m := new(OrderBookUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketDataServiceClient) GetRecentTrades(ctx context.Context, in *GetRecentTradesRequest, opts ...grpc.CallOption) (*GetRecentTradesResponse, error) {
	out := new(GetRecentTradesResponse)
	err := c.cc.Invoke(ctx, "/matchengine.MarketDataService/GetRecentTrades", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketDataServiceClient) SubscribeTrades(ctx context.Context, in *SubscribeTradesRequest, opts ...grpc.CallOption) (MarketDataService_SubscribeTradesClient, error) {
	stream, err := c.cc.NewStream(ctx, &MarketDataService_ServiceDesc.Streams[1], "/matchengine.MarketDataService/SubscribeTrades", opts...)
	if err != nil {
		return nil, err
	}
	x := &marketDataServiceSubscribeTradesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type MarketDataService_SubscribeTradesClient interface {
	Recv() (*Trade, error)
	grpc.ClientStream
}

type marketDataServiceSubscribeTradesClient struct {
	grpc.ClientStream
}

func (x *marketDataServiceSubscribeTradesClient) Recv() (*Trade, error) {
	m := new(Trade)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *marketDataServiceClient) GetTicker(ctx context.Context, in *GetTickerRequest, opts ...grpc.CallOption) (*GetTickerResponse, error) {
	out := new(GetTickerResponse)
	err := c.cc.Invoke(ctx, "/matchengine.MarketDataService/GetTicker", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketDataServiceServer is the server API for MarketDataService service.
// All implementations must embed UnimplementedMarketDataServiceServer
// for forward compatibility
type MarketDataServiceServer interface {
	// 获取订单簿快照
	GetOrderBook(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error)
	// 订阅订单簿更新
	SubscribeOrderBook(*SubscribeOrderBookRequest, MarketDataService_SubscribeOrderBookServer) error
	// 获取最近成交
	GetRecentTrades(context.Context, *GetRecentTradesRequest) (*GetRecentTradesResponse, error)
	// 订阅成交
	SubscribeTrades(*SubscribeTradesRequest, MarketDataService_SubscribeTradesServer) error
	// 获取行情数据
	GetTicker(context.Context, *GetTickerRequest) (*GetTickerResponse, error)
	mustEmbedUnimplementedMarketDataServiceServer()
}

// UnimplementedMarketDataServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMarketDataServiceServer struct {
}

func (UnimplementedMarketDataServiceServer) GetOrderBook(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrderBook not implemented")
}
func (UnimplementedMarketDataServiceServer) SubscribeOrderBook(*SubscribeOrderBookRequest, MarketDataService_SubscribeOrderBookServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeOrderBook not implemented")
}
func (UnimplementedMarketDataServiceServer) GetRecentTrades(context.Context, *GetRecentTradesRequest) (*GetRecentTradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRecentTrades not implemented")
}
func (UnimplementedMarketDataServiceServer) SubscribeTrades(*SubscribeTradesRequest, MarketDataService_SubscribeTradesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeTrades not implemented")
}
func (UnimplementedMarketDataServiceServer) GetTicker(context.Context, *GetTickerRequest) (*GetTickerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicker not implemented")
}
func (UnimplementedMarketDataServiceServer) mustEmbedUnimplementedMarketDataServiceServer() {}

// UnsafeMarketDataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketDataServiceServer will
// result in compilation errors.
type UnsafeMarketDataServiceServer interface {
	mustEmbedUnimplementedMarketDataServiceServer()
}

func RegisterMarketDataServiceServer(s grpc.ServiceRegistrar, srv MarketDataServiceServer) {
	s.RegisterService(&MarketDataService_ServiceDesc, srv)
}

func _MarketDataService_GetOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.MarketDataService/GetOrderBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetOrderBook(ctx, req.(*GetOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_SubscribeOrderBook_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeOrderBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServiceServer).SubscribeOrderBook(m, &marketDataServiceSubscribeOrderBookServer{stream})
}

type MarketDataService_SubscribeOrderBookServer interface {
	Send(*OrderBookUpdate) error
	grpc.ServerStream
}

type marketDataServiceSubscribeOrderBookServer struct {
	grpc.ServerStream
}

func (x *marketDataServiceSubscribeOrderBookServer) Send(m *OrderBookUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketDataService_GetRecentTrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecentTradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetRecentTrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.MarketDataService/GetRecentTrades",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetRecentTrades(ctx, req.(*GetRecentTradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketDataService_SubscribeTrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeTradesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MarketDataServiceServer).SubscribeTrades(m, &marketDataServiceSubscribeTradesServer{stream})
}

type MarketDataService_SubscribeTradesServer interface {
	Send(*Trade) error
	grpc.ServerStream
}

type marketDataServiceSubscribeTradesServer struct {
	grpc.ServerStream
}

func (x *marketDataServiceSubscribeTradesServer) Send(m *Trade) error {
	return x.ServerStream.SendMsg(m)
}

func _MarketDataService_GetTicker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTickerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketDataServiceServer).GetTicker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.MarketDataService/GetTicker",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketDataServiceServer).GetTicker(ctx, req.(*GetTickerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketDataService_ServiceDesc is the grpc.ServiceDesc for MarketDataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketDataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchengine.MarketDataService",
	HandlerType: (*MarketDataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOrderBook",
			Handler:    _MarketDataService_GetOrderBook_Handler,
		},
		{
			MethodName: "GetRecentTrades",
			Handler:    _MarketDataService_GetRecentTrades_Handler,
		},
		{
			MethodName: "GetTicker",
			Handler:    _MarketDataService_GetTicker_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeOrderBook",
			Handler:       _MarketDataService_SubscribeOrderBook_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeTrades",
			Handler:       _MarketDataService_SubscribeTrades_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "match_engine.proto",
}

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	// 添加交易对
	AddSymbol(ctx context.Context, in *AddSymbolRequest, opts ...grpc.CallOption) (*AddSymbolResponse, error)
	// 移除交易对
	RemoveSymbol(ctx context.Context, in *RemoveSymbolRequest, opts ...grpc.CallOption) (*RemoveSymbolResponse, error)
	// 暂停交易
	PauseTrading(ctx context.Context, in *PauseTradingRequest, opts ...grpc.CallOption) (*PauseTradingResponse, error)
	// 恢复交易
	ResumeTrading(ctx context.Context, in *ResumeTradingRequest, opts ...grpc.CallOption) (*ResumeTradingResponse, error)
	// 开始集合竞价
	StartAuction(ctx context.Context, in *StartAuctionRequest, opts ...grpc.CallOption) (*StartAuctionResponse, error)
	// 结束集合竞价
	EndAuction(ctx context.Context, in *EndAuctionRequest, opts ...grpc.CallOption) (*EndAuctionResponse, error)
	// 获取系统状态
	GetSystemStatus(ctx context.Context, in *GetSystemStatusRequest, opts ...grpc.CallOption) (*GetSystemStatusResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) AddSymbol(ctx context.Context, in *AddSymbolRequest, opts ...grpc.CallOption) (*AddSymbolResponse, error) {
	out := new(AddSymbolResponse)
	err := c.cc.Invoke(ctx, "/matchengine.AdminService/AddSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) RemoveSymbol(ctx context.Context, in *RemoveSymbolRequest, opts ...grpc.CallOption) (*RemoveSymbolResponse, error) {
	out := new(RemoveSymbolResponse)
	err := c.cc.Invoke(ctx, "/matchengine.AdminService/RemoveSymbol", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) PauseTrading(ctx context.Context, in *PauseTradingRequest, opts ...grpc.CallOption) (*PauseTradingResponse, error) {
	out := new(PauseTradingResponse)
	err := c.cc.Invoke(ctx, "/matchengine.AdminService/PauseTrading", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) ResumeTrading(ctx context.Context, in *ResumeTradingRequest, opts ...grpc.CallOption) (*ResumeTradingResponse, error) {
	out := new(ResumeTradingResponse)
	err := c.cc.Invoke(ctx, "/matchengine.AdminService/ResumeTrading", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StartAuction(ctx context.Context, in *StartAuctionRequest, opts ...grpc.CallOption) (*StartAuctionResponse, error) {
	out := new(StartAuctionResponse)
	err := c.cc.Invoke(ctx, "/matchengine.AdminService/StartAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) EndAuction(ctx context.Context, in *EndAuctionRequest, opts ...grpc.CallOption) (*EndAuctionResponse, error) {
	out := new(EndAuctionResponse)
	err := c.cc.Invoke(ctx, "/matchengine.AdminService/EndAuction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) GetSystemStatus(ctx context.Context, in *GetSystemStatusRequest, opts ...grpc.CallOption) (*GetSystemStatusResponse, error) {
	out := new(GetSystemStatusResponse)
	err := c.cc.Invoke(ctx, "/matchengine.AdminService/GetSystemStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility
type AdminServiceServer interface {
	// 添加交易对
	AddSymbol(context.Context, *AddSymbolRequest) (*AddSymbolResponse, error)
	// 移除交易对
	RemoveSymbol(context.Context, *RemoveSymbolRequest) (*RemoveSymbolResponse, error)
	// 暂停交易
	PauseTrading(context.Context, *PauseTradingRequest) (*PauseTradingResponse, error)
	// 恢复交易
	ResumeTrading(context.Context, *ResumeTradingRequest) (*ResumeTradingResponse, error)
	// 开始集合竞价
	StartAuction(context.Context, *StartAuctionRequest) (*StartAuctionResponse, error)
	// 结束集合竞价
	EndAuction(context.Context, *EndAuctionRequest) (*EndAuctionResponse, error)
	// 获取系统状态
	GetSystemStatus(context.Context, *GetSystemStatusRequest) (*GetSystemStatusResponse, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (UnimplementedAdminServiceServer) AddSymbol(context.Context, *AddSymbolRequest) (*AddSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSymbol not implemented")
}
func (UnimplementedAdminServiceServer) RemoveSymbol(context.Context, *RemoveSymbolRequest) (*RemoveSymbolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveSymbol not implemented")
}
func (UnimplementedAdminServiceServer) PauseTrading(context.Context, *PauseTradingRequest) (*PauseTradingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseTrading not implemented")
}
func (UnimplementedAdminServiceServer) ResumeTrading(context.Context, *ResumeTradingRequest) (*ResumeTradingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeTrading not implemented")
}
func (UnimplementedAdminServiceServer) StartAuction(context.Context, *StartAuctionRequest) (*StartAuctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartAuction not implemented")
}
func (UnimplementedAdminServiceServer) EndAuction(context.Context, *EndAuctionRequest) (*EndAuctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndAuction not implemented")
}
func (UnimplementedAdminServiceServer) GetSystemStatus(context.Context, *GetSystemStatusRequest) (*GetSystemStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSystemStatus not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_AddSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AddSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.AdminService/AddSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AddSymbol(ctx, req.(*AddSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_RemoveSymbol_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSymbolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).RemoveSymbol(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.AdminService/RemoveSymbol",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).RemoveSymbol(ctx, req.(*RemoveSymbolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_PauseTrading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PauseTradingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).PauseTrading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.AdminService/PauseTrading",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).PauseTrading(ctx, req.(*PauseTradingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_ResumeTrading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeTradingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).ResumeTrading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.AdminService/ResumeTrading",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).ResumeTrading(ctx, req.(*ResumeTradingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StartAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartAuctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StartAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.AdminService/StartAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StartAuction(ctx, req.(*StartAuctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_EndAuction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndAuctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).EndAuction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.AdminService/EndAuction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).EndAuction(ctx, req.(*EndAuctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_GetSystemStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSystemStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).GetSystemStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.AdminService/GetSystemStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).GetSystemStatus(ctx, req.(*GetSystemStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchengine.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSymbol",
			Handler:    _AdminService_AddSymbol_Handler,
		},
		{
			MethodName: "RemoveSymbol",
			Handler:    _AdminService_RemoveSymbol_Handler,
		},
		{
			MethodName: "PauseTrading",
			Handler:    _AdminService_PauseTrading_Handler,
		},
		{
			MethodName: "ResumeTrading",
			Handler:    _AdminService_ResumeTrading_Handler,
		},
		{
			MethodName: "StartAuction",
			Handler:    _AdminService_StartAuction_Handler,
		},
		{
			MethodName: "EndAuction",
			Handler:    _AdminService_EndAuction_Handler,
		},
		{
			MethodName: "GetSystemStatus",
			Handler:    _AdminService_GetSystemStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "match_engine.proto",
}

// ContractServiceClient is the client API for ContractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ContractServiceClient interface {
	// 创建合约订单
	CreateContractOrder(ctx context.Context, in *CreateContractOrderRequest, opts ...grpc.CallOption) (*CreateContractOrderResponse, error)
	// 平仓
	ClosePosition(ctx context.Context, in *ClosePositionRequest, opts ...grpc.CallOption) (*ClosePositionResponse, error)
	// 获取仓位
	GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*GetPositionResponse, error)
	// 获取用户所有仓位
	GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error)
	// 修改杠杆
	ChangeLeverage(ctx context.Context, in *ChangeLeverageRequest, opts ...grpc.CallOption) (*ChangeLeverageResponse, error)
	// 修改保证金模式
	ChangeMarginType(ctx context.Context, in *ChangeMarginTypeRequest, opts ...grpc.CallOption) (*ChangeMarginTypeResponse, error)
	// 获取资金费率
	GetFundingRate(ctx context.Context, in *GetFundingRateRequest, opts ...grpc.CallOption) (*GetFundingRateResponse, error)
	// 订阅仓位更新
	SubscribePositions(ctx context.Context, in *SubscribePositionsRequest, opts ...grpc.CallOption) (ContractService_SubscribePositionsClient, error)
	// 订阅强平事件
	SubscribeLiquidations(ctx context.Context, in *SubscribeLiquidationsRequest, opts ...grpc.CallOption) (ContractService_SubscribeLiquidationsClient, error)
}

type contractServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContractServiceClient(cc grpc.ClientConnInterface) ContractServiceClient {
	return &contractServiceClient{cc}
}

func (c *contractServiceClient) CreateContractOrder(ctx context.Context, in *CreateContractOrderRequest, opts ...grpc.CallOption) (*CreateContractOrderResponse, error) {
	out := new(CreateContractOrderResponse)
	err := c.cc.Invoke(ctx, "/matchengine.ContractService/CreateContractOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) ClosePosition(ctx context.Context, in *ClosePositionRequest, opts ...grpc.CallOption) (*ClosePositionResponse, error) {
	out := new(ClosePositionResponse)
	err := c.cc.Invoke(ctx, "/matchengine.ContractService/ClosePosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) GetPosition(ctx context.Context, in *GetPositionRequest, opts ...grpc.CallOption) (*GetPositionResponse, error) {
	out := new(GetPositionResponse)
	err := c.cc.Invoke(ctx, "/matchengine.ContractService/GetPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) GetUserPositions(ctx context.Context, in *GetUserPositionsRequest, opts ...grpc.CallOption) (*GetUserPositionsResponse, error) {
	out := new(GetUserPositionsResponse)
	err := c.cc.Invoke(ctx, "/matchengine.ContractService/GetUserPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) ChangeLeverage(ctx context.Context, in *ChangeLeverageRequest, opts ...grpc.CallOption) (*ChangeLeverageResponse, error) {
	out := new(ChangeLeverageResponse)
	err := c.cc.Invoke(ctx, "/matchengine.ContractService/ChangeLeverage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) ChangeMarginType(ctx context.Context, in *ChangeMarginTypeRequest, opts ...grpc.CallOption) (*ChangeMarginTypeResponse, error) {
	out := new(ChangeMarginTypeResponse)
	err := c.cc.Invoke(ctx, "/matchengine.ContractService/ChangeMarginType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) GetFundingRate(ctx context.Context, in *GetFundingRateRequest, opts ...grpc.CallOption) (*GetFundingRateResponse, error) {
	out := new(GetFundingRateResponse)
	err := c.cc.Invoke(ctx, "/matchengine.ContractService/GetFundingRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) SubscribePositions(ctx context.Context, in *SubscribePositionsRequest, opts ...grpc.CallOption) (ContractService_SubscribePositionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ContractService_ServiceDesc.Streams[0], "/matchengine.ContractService/SubscribePositions", opts...)
	if err != nil {
		return nil, err
	}
	x := &contractServiceSubscribePositionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ContractService_SubscribePositionsClient interface {
	Recv() (*PositionUpdate, error)
	grpc.ClientStream
}

type contractServiceSubscribePositionsClient struct {
	grpc.ClientStream
}

func (x *contractServiceSubscribePositionsClient) Recv() (*PositionUpdate, error) {
	m := new(PositionUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *contractServiceClient) SubscribeLiquidations(ctx context.Context, in *SubscribeLiquidationsRequest, opts ...grpc.CallOption) (ContractService_SubscribeLiquidationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ContractService_ServiceDesc.Streams[1], "/matchengine.ContractService/SubscribeLiquidations", opts...)
	if err != nil {
		return nil, err
	}
	x := &contractServiceSubscribeLiquidationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ContractService_SubscribeLiquidationsClient interface {
	Recv() (*LiquidationEvent, error)
	grpc.ClientStream
}

type contractServiceSubscribeLiquidationsClient struct {
	grpc.ClientStream
}

func (x *contractServiceSubscribeLiquidationsClient) Recv() (*LiquidationEvent, error) {
	m := new(LiquidationEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ContractServiceServer is the server API for ContractService service.
// All implementations must embed UnimplementedContractServiceServer
// for forward compatibility
type ContractServiceServer interface {
	// 创建合约订单
	CreateContractOrder(context.Context, *CreateContractOrderRequest) (*CreateContractOrderResponse, error)
	// 平仓
	ClosePosition(context.Context, *ClosePositionRequest) (*ClosePositionResponse, error)
	// 获取仓位
	GetPosition(context.Context, *GetPositionRequest) (*GetPositionResponse, error)
	// 获取用户所有仓位
	GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsResponse, error)
	// 修改杠杆
	ChangeLeverage(context.Context, *ChangeLeverageRequest) (*ChangeLeverageResponse, error)
	// 修改保证金模式
	ChangeMarginType(context.Context, *ChangeMarginTypeRequest) (*ChangeMarginTypeResponse, error)
	// 获取资金费率
	GetFundingRate(context.Context, *GetFundingRateRequest) (*GetFundingRateResponse, error)
	// 订阅仓位更新
	SubscribePositions(*SubscribePositionsRequest, ContractService_SubscribePositionsServer) error
	// 订阅强平事件
	SubscribeLiquidations(*SubscribeLiquidationsRequest, ContractService_SubscribeLiquidationsServer) error
	mustEmbedUnimplementedContractServiceServer()
}

// UnimplementedContractServiceServer must be embedded to have forward compatible implementations.
type UnimplementedContractServiceServer struct {
}

func (UnimplementedContractServiceServer) CreateContractOrder(context.Context, *CreateContractOrderRequest) (*CreateContractOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateContractOrder not implemented")
}
func (UnimplementedContractServiceServer) ClosePosition(context.Context, *ClosePositionRequest) (*ClosePositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClosePosition not implemented")
}
func (UnimplementedContractServiceServer) GetPosition(context.Context, *GetPositionRequest) (*GetPositionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPosition not implemented")
}
func (UnimplementedContractServiceServer) GetUserPositions(context.Context, *GetUserPositionsRequest) (*GetUserPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPositions not implemented")
}
func (UnimplementedContractServiceServer) ChangeLeverage(context.Context, *ChangeLeverageRequest) (*ChangeLeverageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeLeverage not implemented")
}
func (UnimplementedContractServiceServer) ChangeMarginType(context.Context, *ChangeMarginTypeRequest) (*ChangeMarginTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeMarginType not implemented")
}
func (UnimplementedContractServiceServer) GetFundingRate(context.Context, *GetFundingRateRequest) (*GetFundingRateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFundingRate not implemented")
}
func (UnimplementedContractServiceServer) SubscribePositions(*SubscribePositionsRequest, ContractService_SubscribePositionsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribePositions not implemented")
}
func (UnimplementedContractServiceServer) SubscribeLiquidations(*SubscribeLiquidationsRequest, ContractService_SubscribeLiquidationsServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeLiquidations not implemented")
}
func (UnimplementedContractServiceServer) mustEmbedUnimplementedContractServiceServer() {}

// UnsafeContractServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractServiceServer will
// result in compilation errors.
type UnsafeContractServiceServer interface {
	mustEmbedUnimplementedContractServiceServer()
}

func RegisterContractServiceServer(s grpc.ServiceRegistrar, srv ContractServiceServer) {
	s.RegisterService(&ContractService_ServiceDesc, srv)
}

func _ContractService_CreateContractOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateContractOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).CreateContractOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.ContractService/CreateContractOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).CreateContractOrder(ctx, req.(*CreateContractOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_ClosePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClosePositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).ClosePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.ContractService/ClosePosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).ClosePosition(ctx, req.(*ClosePositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_GetPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).GetPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.ContractService/GetPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).GetPosition(ctx, req.(*GetPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_GetUserPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).GetUserPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.ContractService/GetUserPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).GetUserPositions(ctx, req.(*GetUserPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_ChangeLeverage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeLeverageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).ChangeLeverage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.ContractService/ChangeLeverage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).ChangeLeverage(ctx, req.(*ChangeLeverageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_ChangeMarginType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMarginTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).ChangeMarginType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.ContractService/ChangeMarginType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).ChangeMarginType(ctx, req.(*ChangeMarginTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_GetFundingRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundingRateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).GetFundingRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/matchengine.ContractService/GetFundingRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).GetFundingRate(ctx, req.(*GetFundingRateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_SubscribePositions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribePositionsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContractServiceServer).SubscribePositions(m, &contractServiceSubscribePositionsServer{stream})
}

type ContractService_SubscribePositionsServer interface {
	Send(*PositionUpdate) error
	grpc.ServerStream
}

type contractServiceSubscribePositionsServer struct {
	grpc.ServerStream
}

func (x *contractServiceSubscribePositionsServer) Send(m *PositionUpdate) error {
	return x.ServerStream.SendMsg(m)
}

func _ContractService_SubscribeLiquidations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeLiquidationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ContractServiceServer).SubscribeLiquidations(m, &contractServiceSubscribeLiquidationsServer{stream})
}

type ContractService_SubscribeLiquidationsServer interface {
	Send(*LiquidationEvent) error
	grpc.ServerStream
}

type contractServiceSubscribeLiquidationsServer struct {
	grpc.ServerStream
}

func (x *contractServiceSubscribeLiquidationsServer) Send(m *LiquidationEvent) error {
	return x.ServerStream.SendMsg(m)
}

// ContractService_ServiceDesc is the grpc.ServiceDesc for ContractService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchengine.ContractService",
	HandlerType: (*ContractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateContractOrder",
			Handler:    _ContractService_CreateContractOrder_Handler,
		},
		{
			MethodName: "ClosePosition",
			Handler:    _ContractService_ClosePosition_Handler,
		},
		{
			MethodName: "GetPosition",
			Handler:    _ContractService_GetPosition_Handler,
		},
		{
			MethodName: "GetUserPositions",
			Handler:    _ContractService_GetUserPositions_Handler,
		},
		{
			MethodName: "ChangeLeverage",
			Handler:    _ContractService_ChangeLeverage_Handler,
		},
		{
			MethodName: "ChangeMarginType",
			Handler:    _ContractService_ChangeMarginType_Handler,
		},
		{
			MethodName: "GetFundingRate",
			Handler:    _ContractService_GetFundingRate_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribePositions",
			Handler:       _ContractService_SubscribePositions_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeLiquidations",
			Handler:       _ContractService_SubscribeLiquidations_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "match_engine.proto",
}
